### ISSUE TITLE
Make GUI themes work

### ISSUE THREAD

**Issue by wvengen** [flathub/org.freedesktop.Sdk.Extension.openjdk17#20]
I started packaging a GUI application and noticed that theme / dpi settings were not properly picked up.
When running the app outside of the flatpak, the app was shown as expected, but when running within the flatpak, fonts sizes were picked up, but some content was not dpi scaled, and the dark theme was not applied everywhere.

After some experimentation (and analzying strace output), it turns out `xrdb` is used to get these settings. Adding the following module fixed the problem:

```yaml
name: xrdb
sources:
  - type: archive
    url: https://www.x.org/releases/individual/app/xrdb-1.2.2.tar.gz
    sha256: db2d774a35ae2f7e7ac61cc2de0dcae27fc2aa14399c35721f8300e63ea73549
    x-checker-data:
      type: html
      url: https://www.x.org/releases/individual/app/
      pattern: (xrdb-(\d\.\d+\.?\d*).tar.gz)
cleanup:
  - /share/man
modules:
  - name: libXmu
    cleanup:
      - /include
      - /lib/*.a
      - /lib/pkgconfig
      - /share/doc
    sources:
      - type: archive
        url: https://www.x.org/releases/individual/lib/libXmu-1.1.4.tar.gz
        sha256: 3091d711cdc1d8ea0f545a13b90d1464c3c3ab64778fd121f0d789b277a80289
        x-checker-data:
          type: html
          url: https://www.x.org/releases/individual/lib/
          pattern: (libXmu-(\d\.\d+\.?\d*).tar.gz)
```

(Based on [MEGAsync](https://github.com/flathub/nz.mega.MEGAsync/blob/master/nz.mega.MEGAsync.yml), which needs xrdb even though it doesn't use Java.)

If this applies to multiple GUI applications, it could make sense to include this in the OpenJDK17 extension.
